/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: A18K (https://sketchfab.com/A18K)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/old-chair-6e35f6fdf1264db4880049b802f18ea2
Title: Old Chair
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Chair(props) {
  const { nodes, materials } = useGLTF('./models/old_chair.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.006}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube1629_Material1257565_0.geometry}
            material={materials['Material.1257565']}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./models/old_chair.glb')
