/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Computers(props) {
  const { nodes, materials } = useGLTF('./models/asdasd.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_221.geometry}
        material={materials.Texture}
        position={[-0.947, 2.427, -0.538]}
        rotation={[0, 0.967, 0]}
        scale={0.457}
      />
    </group>
  )
}

useGLTF.preload('./models/asdasd.glb')
