/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { Suspense, useRef } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import useStore from "../store";
import GetSongs from "../_components/GetSongs";

export default function Cover(props) {
  const currentImage = useStore((state) => state.currentImageHigh);
  const texture = useTexture(currentImage || "/images/default.jpeg");

  texture.flipY = false;

  const { nodes, materials } = useGLTF("./models/vinyl-box-face.glb");
  return (
    <>
      <GetSongs />

      <group {...props} dispose={null}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane.geometry}
          position={[2.109, 0.216, 0.616]}
          rotation={[Math.PI / 2, 1.216, -Math.PI / 2]}
          scale={0.401}
        >
          <meshBasicMaterial map={texture} />
        </mesh>
      </group>
    </>
  );
}

useGLTF.preload("./models/vinyl-box-face.glb");
