/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: artikora (https://sketchfab.com/artikora978)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/old-stylized-gramophone-2db8afb8494a44809d6bd65b7a65d074
Title: Old  Stylized Gramophone
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export default function Gramaphone(props) {
  const { nodes, materials } = useGLTF("./models/2.glb");
  const meshRef1 = useRef();
  const meshRef2 = useRef();

  useFrame((state, delta) => {
    if (meshRef1.current && meshRef2.current) {
      meshRef1.current.rotation.z += delta * 2;
      meshRef2.current.rotation.z += delta * 2;
    }
  });
  return (
    <group
      {...props}
      position={[-3, 0, 0]}
      rotation={[0, Math.PI / 1.3, 0]}
      dispose={null}
    >
      <group position={[0, 0.091, 0]} rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[-27.453, 29.262, -1.284]} scale={100}>
            <group
              position={[-0.086, -0.007, -0.559]}
              rotation={[0, 0, -Math.PI]}
              scale={-1}
            >
              <mesh
                ref={meshRef1}
                castShadow
                receiveShadow
                geometry={nodes.pCube2001_Material001_0001.geometry}
                material={materials["Material.003"]}
              />
              <mesh
                ref={meshRef2}
                castShadow
                receiveShadow
                geometry={nodes.pCube2001_Material001_0001_1.geometry}
                material={materials["Material.002"]}
              />
            </group>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pCube2001_Material001_0.geometry}
              material={materials["Material.003"]}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube2_Material_0.geometry}
            material={materials["Material.002"]}
            position={[-27.453, 29.262, -1.284]}
            scale={100}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("./models/2.glb");
