/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Light(props) {
  const { nodes, materials } = useGLTF("./models/light.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Industrial_Light_Industrial_Light_Transparent_0.geometry
        }
        material={materials.Industrial_Light_Transparent}
        position={[-12.702, 0.016, 1.122]}
        rotation={[-Math.PI, 0.749, -Math.PI]}
        scale={0.023}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Industrial_Light_Industrial_Light_0.geometry}
        material={materials.Industrial_Light}
        position={[-12.702, 0.016, 1.122]}
        rotation={[-Math.PI, 0.749, -Math.PI]}
        scale={0.023}
      />
    </group>
  );
}

useGLTF.preload("./models/light.glb");
