/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function VinylPlayer(props) {
  const { nodes, materials } = useGLTF("./models/vinyl-player.glb");
  return (
    <group {...props} dispose={null}>
      <group
        position={[1.253, 0.336, 0.611]}
        rotation={[0, -0.459, 0]}
        scale={0.571}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube20_ditals_0_1.geometry}
          material={materials.ditals}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube20_ditals_0_2.geometry}
          material={materials.dit2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube20_ditals_0_3.geometry}
          material={materials.naconez}
        />
      </group>
      <group
        position={[1.224, 0.309, 1.135]}
        rotation={[0, -0.459, 0]}
        scale={0.006}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder3_dit3_0_1.geometry}
          material={materials.dit3}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder3_dit3_0_2.geometry}
          material={materials.dit2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder3_dit3_0_3.geometry}
          material={materials.noska}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder3_dit3_0_4.geometry}
          material={materials.ditals}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder3_dit3_0_5.geometry}
          material={materials.vinil}
        />
      </group>
    </group>
  );
}

useGLTF.preload("./models/vinyl-player.glb");
