/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef, useState } from "react";
import { useGLTF } from "@react-three/drei";
import useCameraRig from "../_hooks/useCameraRig";
import { initialCameraPosition, vinylPosition } from "../_constants/cameraConfig";
import useStore from "../store";

export default function VinylBox({ controlsRef, ...props }) {
  const isVinylSelected = useStore((state) => state.isVinylSelected);
  const setIsVinylSelected = useStore((state) => state.setIsVinylSelected);
  const { nodes, materials } = useGLTF("./models/vinyl-box.glb");
  const moveCamera = useCameraRig(controlsRef);

  useEffect(() => {
    if (!isVinylSelected) {
      moveCamera(initialCameraPosition.position, initialCameraPosition.target);
    }
  }, [isVinylSelected]);

  const handleClick = () => {
    const cameraConfig = vinylPosition[0];
    moveCamera(cameraConfig.position, cameraConfig.target);
    setIsVinylSelected(true);
  };

  return (
    <group {...props} dispose={null}>
      <mesh
        onClick={handleClick}
        castShadow
        receiveShadow
        geometry={nodes.vinyl_box_face.geometry}
        material={materials.dit2}
        position={[-0.023, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("./models/vinyl-box.glb");
