/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function VinylBox(props) {
  const { nodes, materials } = useGLTF("./models/vinyl-box.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.vinyl_box_face.geometry}
        material={materials.dit2}
        position={[-0.023, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("./models/vinyl-box.glb");
